---
#- name: install xdebug
#  action: shell pecl install xdebug
- name: copy z_xdebug.ini into mods-available
  template:
    src=z_xdebug.ini.j2
    dest=/etc/php5/mods-available/z_xdebug.ini
  notify:
    - reload apache
- name: make a symlink to z_xdebug.ini
  file:
    src=/etc/php5/mods-available/z_xdebug.ini
    dest=/etc/php5/apache2/conf.d/z_xdebug.ini
    state=link
  notify:
    - restart apache