---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant/www
    #always set client name to ilias3_unibe to ensure capability with db imports
    default_client: ilias3-unibe
    ilias_name: ilias-test #Directory, where lib is placed into
    mysql_root_password: test1234

    ilias_git_repo: "ssh://git@ilublx3.unibe.ch:ilias/ilias.git"
    ilias_git_version: "develop"

    ilias_db_name: ilias50_innodb_empty
    setup_hash: 16d7a4fca7442dda3ad93c9a726597e4 #password: test1234

    ilias_skin: "default"
    ilias_style: "delos"

    log_dir: "/var/log/ilias"
    logfile_name: "ilias.log"

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - system
    - webserver
    - database
    - ilias
