---
- hosts: all
  sudo: true
  vars:
    document_root: /vagrant/www
    #always set client name to ilias3_unibe to ensure capability with db imports
    default_client: ilias3-unibe
    ilias_name: ilias-test #Directory, where lib is placed into
    mysql_root_password: test1234

    ilias_git_repo: "git@ilublx3.unibe.ch:ilias/ilias.git"

    etherpad_git_repo: "git://github.com/ether/etherpad-lite.git"
    etherpad_destination: "/usr/share/etherpad-lite"
    ilias_git_version: "develop"

    path_to_padjs: "/usr/share/etherpad-lite/src/static/custom/pad.js"
    github_to_padjs: "raw.githubusercontent.com/iLUB/ILIAS-Etherpad-Lite-Plugin/300602ba1e12b72da6440aadf82e553d7463c07a"

    #{{ ilias50_innodb_empty OR ilias50_innodb_testing}}
    ilias_db_name: ilias51
    setup_hash: 16d7a4fca7442dda3ad93c9a726597e4 #password: test1234

    ilias_skin: "default"
    ilias_style: "delos"

    log_dir: "/var/log/ilias"
    logfile_name: "ilias.log"

    etherpad_port: "9703"

    ksl_export_file_name: "LmsLvExport_DE_"
    ksl_memberhsip_file_name: "LmsTeilnehmerExport_"

    #Caching
    cache_user_name: "cache"
    cache_user_password: "test1234"
    apc_cache_size: "256M"
    opcode_cache_size: "512M"

    #optional Role setting
    mariaDB: true
    importDB: true
    etherpad: true
    bugeno: false
    xdebug: true
    hub: false
    lucene: false



  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - system
    - webserver
    - database
    - ilias
    - {role: etherpad, when: etherpad}
    - {role: bugeno, when: bugeno}
    - {role: xdebug, when: xdebug}
    - {role: hub, when: hub}
    - {role: lucene, when: lucene}