## Git Checkout of Etherpad
- name: clone etherpad repo
  git: repo={{ etherpad_git_repo }} dest={{ etherpad_destination }} accept_hostkey=true update=no
- name: chown 775 etherpad-lite
  file: path={{ etherpad_destination }} owner=etherpad-lite group=etherpad-lite mode=0775 state=directory recurse=yes