## Required Tools
- name: install gzip
  apt: name=gzip state=present
- name: install git
  apt: name=git state=present
- name: install curl
  apt: name=curl state=present
- name: install python
  apt: name=python state=present
- name: install libssl-dev
  apt: name=libssl-dev state=present
- name: install pkg-config
  apt: name=pkg-config state=present
- name: install build-essential
  apt: name=build-essential

## can be commented out while developing
##- name: fetch node.js from source
##  action: shell curl -sL https://deb.nodesource.com/setup | sudo bash -
##- name: install nodejs
##  apt: name=nodejs state=present