---
- name: install php
  apt: name=php5 state=present

- name: install apcu
  apt: name=php5-apcu state=present

- name: create cache directory
  file:
    path={{ document_root }}/cache/
    state=directory
    owner=www-data
    group=ilub
    mode=0774

- name: create htpasswd to set limit access of cache directory
  htpasswd: path=/etc/htpasswd/.htpasswd name={{ cache_user_name }} password={{ cache_user_password }} owner=root group=www-data mode=0640

- name: copy apc.php to webroot
  template:
    src=apc.php.j2
    dest={{ document_root }}/cache/apc.php
  notify:
    - reload apache

- name: copy opcode.php to webroot
  template:
    src=opcode.php.j2
    dest={{ document_root }}/cache/opcode.php
  notify:
    - reload apache

- name: copy z_ilias.ini into mods-available
  template:
    src=z_ilias.ini.j2
    dest=/etc/php5/mods-available/z_ilias.ini
  notify:
    - reload apache

- name: copy z_performance_ilias.ini.j2 into mods-available
  template:
    src=z_performance_ilias.ini.j2
    dest=/etc/php5/mods-available/z_performance_ilias.ini
  notify:
    - reload apache

- name: copy z_mail.ini.j2 into mods-available
- name: make a symlink to z_ilias.ini
  file:
    src=/etc/php5/mods-available/z_ilias.ini
    dest=/etc/php5/apache2/conf.d/z_ilias.ini
    state=link
  notify:
    - restart apache

- name: make a symlink to z_performance_ilias.ini
  file:
    src=/etc/php5/mods-available/z_performance_ilias.ini
    dest=/etc/php5/apache2/conf.d/z_performance_ilias.ini
    state=link
  notify:
    - restart apache

- name: make a symlink to z_mail.ini
  file:
    src=/etc/php5/mods-available/z_mail.ini
    dest=/etc/php5/apache2/conf.d/z_mail.ini
    state=link
  notify:
    - restart apache

- name: make a symlink to z_mail.ini for cli
  file:
    src=/etc/php5/mods-available/z_mail.ini
    dest=/etc/php5/cli/conf.d/z_mail.ini
    state=link
  notify:
    - restart apache

